# 처리 단계 설정
steps:
  download_from_s3: False    # S3에서 다운로드 여부
  segment_lungs: False        # 폐 분할 여부
  preprocess_images: True     # 이미지 전처리 여부
  upload_to_s3: False          # S3에 업로드 여부

# S3 설정
s3:
  bucket_name: "${S3_BUCKET_NAME}"  # S3 버킷 이름
  prefix: "cxr-pneumonia-2"
  input_prefix: "raw"
  segmented_prefix: "segmented"
  preprocessed_prefix: "preprocessed"

# 디렉토리 설정
directories:
  data_dir: "data"          # 데이터 디렉토리
  input_dir: "raw"          # 원본 데이터 디렉토리
  segmented_dir: "segmented"     # 폐 분할 결과 디렉토리
  preprocessed_dir: "preprocessed"  # 전처리 결과 디렉토리

# 전처리 설정
preprocessing:
  # 적용할 전처리 단계 (True/False로 설정)
  steps:
    convert_grayscale: True
    apply_clahe: True
    apply_gaussian_blur: True
    apply_min_max_stretch: True
    apply_sharpening: True
    convert_to_rgb: True
  
  # 전처리 파라미터
  params:
    clahe:
      clip_limit: 2.0
      grid_size: [8, 8]
    gaussian_blur:
      radius: 1.0
    min_max_stretch:
      lower_percentile: 1
      upper_percentile: 99
    sharpening:
      radius: 2
      percent: 150
      threshold: 3