# SageMaker 훈련 설정
entry_point: "densenet121.py"
source_dir: "models"
instance_count: 1
instance_type: "ml.g4dn.xlarge"  # GPU 인스턴스
framework_version: "1.13.1"  # 안정적인 PyTorch 버전
py_version: "py39"    # Python 3.9로 다운그레이드
base_job_name: "aws-say1-4team"  # SageMaker 작업 이름

# 데이터 설정
s3:
  bucket_name: "${S3_BUCKET_NAME}"  # S3 버킷 이름
  prefix: "cxr-pneumonia-4"
  train_prefix: "raw/train"
  val_prefix: "raw/val"
  test_prefix: "raw/test"
local:
  data_dir: "../data"  # 로컬 데이터 디렉토리
  train_dir: "train"
  val_dir: "val"
  test_dir: "test"

# MLflow 설정
mlflow: null
  #tracking_uri: "http://your-mlflow-server:5000"
 # experiment_name: "pneumoniaClassification"

# 하이퍼파라미터
hyperparameters:
  epochs: 200
  batch-size: 32
  learning-rate: 1e-5
  model-type: "densenet121"
  num-classes: 3
  patience: 10