version: '3.7'

services:
  orthanc:
    image: jodogne/orthanc-plugins
    container_name: orthanc
    ports:
      - "8042:8042"  # HTTP UI
      - "4242:4242"  # DICOM
    environment:
      ORTHANC__Name: "Orthanc"
      ORTHANC__RemoteAccessAllowed: "true"
      ORTHANC__DicomWeb__Enable: "true"
      ORTHANC__DicomWeb__Root: "/dicom-web/"
      ORTHANC__DicomWeb__EnableWado: "true"
      ORTHANC__PluginsEnabled: "true"
    volumes:
      - orthanc-data:/var/lib/orthanc/db

  ohif:
    image: ohif/viewer
    container_name: ohif
    ports:
      - "80:80"
    environment:
      - APP_CONFIG=config.json
    volumes:
      - ./config:/usr/share/nginx/html/config

volumes:
  orthanc-data: